### ISSUE TITLE
The model creates artifacts in images with low texture

### ISSUE THREAD

**Issue by raminia** [KupynOrest/DeblurGAN#27]
Hi,

Great work. I noticed that the provided trained model creates significant artifacts when the input images contains minimal texture. For example, if you tile a larger image and feed it into the system the areas such as smooth walls/surfaces will have artifacts that resemble JPG artifacts. I wonder if that relates to the training set you used.

**Comment by KupynOrest** [comment]
Hi, 

Thanks a lot. I can confirm that there is a problem when running the model on high res images with low texture, it is mostly due to the dataset, as the model was trained on lower resolution and with high texture details. In many cases, downsampling by a factor of 2 -> deblurring -> upsampling might improve the results a lot.

**Comment by raminia** [comment]
Thanks for confirming the issue. I'm planning to retrain the model with data that contains samples with low/minimal texture in hope of fixing these issues.
